### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by Mickeyyyang** [RoyE3BBB/DQL#1]
您好，打扰了，我最近刚开始看用RL走迷宫的知识，有个问题想请教一下：
（1）想要运行您改为TF2.0版本的代码，环境配置上有具体的要求吗？
（2）maze部分完成的是不是只是一个train的过程，如果想要进一步进行predict的话，应该做些什么更改呢？
谢谢~

**Comment by RoyE3BBB** [comment]
> 您好，打扰了，我最近刚开始看用RL走迷宫的知识，有个问题想请教一下：
> （1）想要运行您改为TF2.0版本的代码，环境配置上有具体的要求吗？
> （2）maze部分完成的是不是只是一个train的过程，如果想要进一步进行predict的话，应该做些什么更改呢？
> 谢谢~

环境配置上是没什么特别要求的，tensorflow在2.0以上就好了。
在2.0的kears里，神经网络的操作都是通过model完成的。你想predict的话，利用brain里的self.target_net.predict()就好了。感觉你可以先去看看2.0的基础教程https://www.tensorflow.org/tutorials?hl=zh-cn
